MODULE_SIZE = 128
OUTPUT_CHANNELS = 3
SRC_PATH = 'D:/PyCharm 2021.1.3/PycharmProjects/flatangleAPI/Segmentation/UNet/src'
IMG_PATH = SRC_PATH + '/img'
MASK_PATH = SRC_PATH + '/mask'
DATASET_PATH = SRC_PATH + '/dataset'
MODULE_PATH = SRC_PATH + '/model'
UN_PRODUCED_FILE_PTAH = r'D:\PyCharm 2021.1.3\PycharmProjects\flatangleAPI\before'
PRODUCED_FILE_PATH = SRC_PATH + '/../aft'
EPOCHS_NUM = 10
